GET http://localhost:3000/student
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
"email": "somet1@gmail.com","username": "some1", "password":"123"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "username": "some1", "password":"123"
}