GET http://localhost:3000/student
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
 "firstName":"mashuuu", "lastName":"tov","email": "somet12@gmail.com","username": "some12", "password":"1232"
}
###
//login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "username": "some16", "password":"123"
}
###
GET http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYzMDI3NjFhYTgxYjY0YTQzMDY0MjMiLCJpYXQiOjE3MTA0MzEzOTB9.9YSz6OXgbFhksbjMhA-1HfsbE3eCKTv3QLmTzUMTqjk
###
GET http://localhost:3000/auth/refresh
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYzMDI3NjFhYTgxYjY0YTQzMDY0MjMiLCJpYXQiOjE3MTA0MzcyMzZ9.f0biw60wqyoRqrfkYSZsxqqNPB_e7NPqskVwxZCQ5pE
###
PUT http://localhost:3000/user/65f33f7987937e974c371ad6
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYzMDI3NjFhYTgxYjY0YTQzMDY0MjMiLCJpYXQiOjE3MTA0MzcyMzZ9.f0biw60wqyoRqrfkYSZsxqqNPB_e7NPqskVwxZCQ5pE

{
    "email":"mashu2", "username": "some16", "password":"123"
}